### ISSUE TITLE
strange issue with 

### ISSUE THREAD

**Issue by hongdavid94** [simongraham/hovernet_inference#56]
Hi thank you for writing this package, I am encountering some issue that I cannot truely resolve on my own... The beginning part (of run.py) works until "infer.load_model()" in run.py. I describe my inputs, environment, and my issue below

CLI command I gave:

```bash
python hovernet_inference/run.py --mode='tile' --model='./hovernet-inference-weights/pannuke.npz' --input_dir='../my/custom/input_dir/' --output_dir='../my/custom/output_dir'
```
output (before the error):
```
{'--batch_size': '25',
 '--cache_dir': 'cache/',
 '--gpu': '0',
 '--help': False,
 '--inf_tile_shape': '15000',
 '--input_dir': '../../sample2/',
 '--mode': 'tile',
 '--model': './hovernet-inference-weights/pannuke.npz',
 '--output_dir': './hover_seg/TCGA/sample1/',
 '--postproc_workers': '10',
 '--proc_tile_shape': '2048',
 '--return_probs': False,
 '--version': False}
 ```
 print statements for my InferTile object's attributes:
```
nr_types: 6
patch_input_shape: [256, 256]
patch_output_shape: [164, 164]
input_norm: True
input_tensor_names: ['images']
output_tensor_names: ['predmap-coded']
model_path: ./hovernet-inference-weights/pannuke.npz
input_dir: ../../custom/input
batch_size: 25
return_probs: False
model_name: pannuke
```
error message
```
Traceback (most recent call last):
  File "/run.py", line 880, in <module>
    infer.load_model()
  File "/run.py", line 215, in load_model
    pred_config = PredictConfig(
  File "/config.py", line 79, in __init__
    self.input_signature = model.get_input_signature()
  File "/argtools.py", line 192, in wrapper
    value = func(*args, **kwargs)
  File "/model_desc.py", line 45, in get_input_signature
    inputs = self.inputs()
  File "/model_desc.py", line 75, in inputs
    raise NotImplementedError()
NotImplementedError
```
class of input in function get_input_signature and its attributes
```
<class 'hover.model.graph.Model_NP_HV'>
#print all attributes from self: 
nr_types: 6
input_shape: [256, 256]
mask_shape: [164, 164]
input_norm: True
data_format: NCHW
_MEMOIZED_CACHE: {}
```

environment (Python 3.10.12), packages and their versions:
```
docopt: 0.6.2
numpy: 1.26.4
tqdm: 4.66.5
six: 1.16.0
wrapt: 1.13.3
gast: 0.5.2
astunparse: 1.6.3
termcolor: 1.1.0
packaging: 21.3
urllib3: 1.26.5
chardet: 4.0.0
certifi: 2020.6.20
idna: 3.3
requests: 2.25.1
h5py: 3.6.0
scipy: 1.12.0
flatbuffers: 1.12.1-git20200711.33e2d80-dfsg1-0.6
jaxlib: 0.4.14
colorama: 0.4.4
jax: 0.4.14
tensorboard: 2.13.0
fsspec: 2024.3.1
pytz: 2022.1
pandas: 1.3.5
keras: 2.13.1
tensorflow: 2.13.1
msgpack: 1.1.0
psutil: 6.0.0
tabulate: 0.9.0
tensorpack: 0.11
pyparsing: 2.4.7
cycler: 0.12.1
kiwisolver: 1.4.7
matplotlib: 3.9.2
lxml: 5.3.0
glymur: 0.13.6
```

Any help is appreciated. Thank you!

**Comment by G-R-0** [comment]
> Hi thank you for writing this package, I am encountering some issue that I cannot truely resolve on my own... The beginning part (of run.py) works until "infer.load_model()" in run.py. I describe my inputs, environment, and my issue below
> 
> CLI command I gave:
> 
> ```shell
> python hovernet_inference/run.py --mode='tile' --model='./hovernet-inference-weights/pannuke.npz' --input_dir='../my/custom/input_dir/' --output_dir='../my/custom/output_dir'
> ```
> 
> output (before the error):
> 
> ```
> {'--batch_size': '25',
>  '--cache_dir': 'cache/',
>  '--gpu': '0',
>  '--help': False,
>  '--inf_tile_shape': '15000',
>  '--input_dir': '../../sample2/',
>  '--mode': 'tile',
>  '--model': './hovernet-inference-weights/pannuke.npz',
>  '--output_dir': './hover_seg/TCGA/sample1/',
>  '--postproc_workers': '10',
>  '--proc_tile_shape': '2048',
>  '--return_probs': False,
>  '--version': False}
> ```
> 
> print statements for my InferTile object's attributes:
> 
> ```
> nr_types: 6
> patch_input_shape: [256, 256]
> patch_output_shape: [164, 164]
> input_norm: True
> input_tensor_names: ['images']
> output_tensor_names: ['predmap-coded']
> model_path: ./hovernet-inference-weights/pannuke.npz
> input_dir: ../../custom/input
> batch_size: 25
> return_probs: False
> model_name: pannuke
> ```
> 
> error message
> 
> ```
> Traceback (most recent call last):
>   File "/run.py", line 880, in <module>
>     infer.load_model()
>   File "/run.py", line 215, in load_model
>     pred_config = PredictConfig(
>   File "/config.py", line 79, in __init__
>     self.input_signature = model.get_input_signature()
>   File "/argtools.py", line 192, in wrapper
>     value = func(*args, **kwargs)
>   File "/model_desc.py", line 45, in get_input_signature
>     inputs = self.inputs()
>   File "/model_desc.py", line 75, in inputs
>     raise NotImplementedError()
> NotImplementedError
> ```
> 
> class of input in function get_input_signature and its attributes
> 
> ```
> <class 'hover.model.graph.Model_NP_HV'>
> #print all attributes from self: 
> nr_types: 6
> input_shape: [256, 256]
> mask_shape: [164, 164]
> input_norm: True
> data_format: NCHW
> _MEMOIZED_CACHE: {}
> ```
> 
> environment (Python 3.10.12), packages and their versions:
> 
> ```
> docopt: 0.6.2
> numpy: 1.26.4
> tqdm: 4.66.5
> six: 1.16.0
> wrapt: 1.13.3
> gast: 0.5.2
> astunparse: 1.6.3
> termcolor: 1.1.0
> packaging: 21.3
> urllib3: 1.26.5
> chardet: 4.0.0
> certifi: 2020.6.20
> idna: 3.3
> requests: 2.25.1
> h5py: 3.6.0
> scipy: 1.12.0
> flatbuffers: 1.12.1-git20200711.33e2d80-dfsg1-0.6
> jaxlib: 0.4.14
> colorama: 0.4.4
> jax: 0.4.14
> tensorboard: 2.13.0
> fsspec: 2024.3.1
> pytz: 2022.1
> pandas: 1.3.5
> keras: 2.13.1
> tensorflow: 2.13.1
> msgpack: 1.1.0
> psutil: 6.0.0
> tabulate: 0.9.0
> tensorpack: 0.11
> pyparsing: 2.4.7
> cycler: 0.12.1
> kiwisolver: 1.4.7
> matplotlib: 3.9.2
> lxml: 5.3.0
> glymur: 0.13.6
> ```
> 
> Any help is appreciated. Thank you!

Sorry to bother you, but I would like to ask if you have resolved this issue. I am facing the same problem as you.

**Comment by G-R-0** [comment]
@hongdavid94 Sorry to bother you, but I would like to ask if you have resolved this issue. I am facing the same problem as you.
